"""empty message

Revision ID: 5dae1027bdd1
Revises: 2d8e09386399
Create Date: 2022-12-15 21:59:53.133347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dae1027bdd1'
down_revision = '2d8e09386399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_order_cart_id_cart', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_order_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_order_cart_id_cart', 'cart', ['cart_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
